### PR TITLE
Add aarch64 to the list of archictectures.

### PR DESCRIPTION
**Pull request by nihilisticpandemonium**
Built and tested on a 8GB Rasperry Pi 4B running Arch Linux Arm.
The patch added to coreutils is also present in the Arch Linux Arm coreutils PKGBUILD it is a backported patch from the next coreutils version that reverts a change that introduced a syscall that is not implemented in arm64.

### CODE REVIEW

**Comment by nihilisticpandemonium** [comment]
img-2021-06-01-032722

I also want to say that the patch from the coreutils github states that the syscall is no longer needed on Linux so I think it would be safe to build on x86_64 as well which is why I added it to the PKGBUILD and didnt try to make it conditional.

**Comment by fishilico** [comment]
Hello, thanks for your Pull Request (and sorry for the delay). Here are a few comments:

* About the coreutils patch, I understand that it is already upstream and I agree to carry it too in coreutils-selinux package. But I know that GitHub may change the content of patches downloaded through the `.patch` URL (I hit this issue a few years ago in https://aur.archlinux.org/cgit/aur.git/commit/?h=setools3-libs&id=500c1d1676756a3227590eb276e21b628df97922) and I would prefer to carry a downloaded patch. Either you modify this Pull Request or I can do it.

* In this PR, you modified some packages which are only present to ease upgrading old systems, such as `ustr-selinux` and `setools3-libs`. I did not expect these packages to be present on new systems. Did you require them for your use-case? If yes, could you share which packages/software still require them (this software would need to be updated)?

Otherwise, looks good to me. I am planning to integrate your PR to all the SELinux packages which are "still current" in a few days (right now I am busy with other work).
Thanks!

**Comment by nihilisticpandemonium** [comment]
I will download the coreutils patch and repush in a moment, honestly, i did a sed replace on all of the PKGBUILDs to add them.  I follow the wiki for installation, so I probably wouldnt have any of those actually installed.  No worries about the delay, Im happy to contribute :)

**Comment by fishilico** [comment]
I merged your patch to every AUR packages that are still current, and merged back (as usual) the changes in this repository: https://github.com/archlinuxhardened/selinux/commits/master?after=3992bfb13aa5b3e859bcbe4ddbad51d0707d3a7c+26&branch=master . So now `aarch64` has been added to the list of architectures.

Closing this PR as it is merged, but if I missed something while doing this split/merge process, please let me know (by posting a comment here/re-opening the PR).

**Pull request closed without merging**
