### PR TITLE
systemd update to 246.1-1

### PR DESCRIPTION
**Pull request by tqre**
Updated systemd version. 
In line with https://www.archlinux.org/packages/core/x86_64/systemd/
Changelog in core repo: https://github.com/archlinux/svntogit-packages/commits/packages/systemd/trunk
Tested it, works on my QEMU setup.

### CODE REVIEW

**Comment by tqre** [comment]
An unused patch removal didn't make it to git for some reason, now it is not there anymore, and the build succeeds.

**Comment by fishilico** [comment]
Thanks for your contribution!
On my test VM, the build succeeds but `check()` fails with:
```text
404/504 test-journal-flush                        FAIL           0.92s (killed by signal 6 SIGABRT)
[...]
Ok:                 489 
Expected Fail:      0   
Fail:               1   
Unexpected Pass:    0   
Skipped:            14  
Timeout:            0   

Full log written to /home/vagrant/.tmp/build/systemd-selinux/src/build/meson-logs/testlog.txt
```

From a shell in the build directory, is seams that `./test-journal-flush` runs fine with `root` privileges but not without:
```console
$ ./test-journal-flush
journal_file_copy_entry failed: Bad message
Assertion 'r >= 0' failed at src/journal/test-journal-flush.c:52, function main(). Aborting.
Aborted (core dumped)

$ sudo ./test-journal-flush
```

Did you encounter this issue? I tried to better understand it but it takes some time, and I do not want to update the package if the update is buggy.

**Comment by tqre** [comment]
I checked my build logs, and the tests go through fine. My builder VM has passwordless sudo configured to minimize interaction and to avoid sudo timeouts.

About my setup: I have a QEMU machine automated to build and configure Arch from scratch all the way to running build_and_install_all.sh

Here are relevant parts from a recent build:
```
Aug 15 14:18:27 build-selinux bash[319126]: [1103/2012] Compiling C object 'test-journal-flush@exe/src_journal_test-journal-flush.c.o'
Aug 15 14:19:40 build-selinux bash[319126]: [1924/2012] Linking target test-journal-flush
Aug 15 14:20:16 build-selinux bash[327893]: 404/504 test-journal-flush                        OK             1.88s
Aug 15 14:23:28 build-selinux bash[393668]: [1104/2012] Compiling C object 'test-journal-flush@exe/src_journal_test-journal-flush.c.o'
Aug 15 14:24:41 build-selinux bash[393668]: [1921/2012] Linking target test-journal-flush
Aug 15 14:25:16 build-selinux bash[402436]: 404/504 test-journal-flush                        OK             1.73s
```

**Comment by fishilico** [comment]
Thanks! It was indeed an issue with a corrupted journal file in my testing environment. Now `systemd-selinux` builds fine.

I upgraded the package in commit https://github.com/archlinuxhardened/selinux/commit/4de7145f34e8ab2fee8eb98378e51fc7e7b7d51f (AUR https://aur.archlinux.org/cgit/aur.git/commit/?h=systemd-selinux&id=4de7145f34e8ab2fee8eb98378e51fc7e7b7d51f). I did not use your PR because you did not remove `0002-make-homed-userdbd-repart-services-installable.patch` from the git repository. There were also other minor differences between your PR and my changes, that would have been fine.

**Pull request closed without merging**
